FROM clickhouse/clickhouse-server:26.2.19.43@sha256:c2f2605585899d5103a0447daadbc0005f362200d5f0fcca7f40db3ca0dd36dd

COPY --chown=clickhouse:clickhouse storage.xml /etc/clickhouse-server/config.d/storage.xml
